name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
# predev = "npm exec prisma generate"
predev = ""
# dev = "npm exec prisma migrate deploy && npm exec react-router dev"
dev = "npm exec react-router dev"
