# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
name = "My Videos"
handle = "My-Videos"
type = "ui_extension"
#type = "customer_account_ui_extension"
uid = "b41be001-abb3-5081-97d2-5367889359b89767f6e7"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/MyVideosPage.jsx"
#target = "customer-account.order-status.block.render"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true     # query storefront API
network_access = true # make external network calls (to backend)
