AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31 # AWS SAM

Description:
  AWS CloudFormation & SAM template for creating resources for the shopify-viewpass backend.


Resources:

  # ---------------------------------------------------------------------------
  # Resource: IAM Execution Role for the Lambda Function
  #           Allow access to DynamoDb and SSM Secret Parameters
  # ---------------------------------------------------------------------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'shopify-app-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # Standard policy to allow writing console logs to CloudWatch
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        # Inline policy allowing the function to interact with other resources
        - PolicyName: DynamoDbTablesAndSSMAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow access to DynamoDb Table
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ProductsTable.Arn
                  - !GetAtt LicencesTable.Arn
              # Allow access to all SSM Parameters
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
              # 2. Allow decrypting the SecureString via KMS
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm'

  # ---------------------------------------------------------------------------
  # Resource: IAM Execution Role for the StepFunctions to read/write
  #           ViewStatsTable, since this doesn't touch the Lambda
  # ---------------------------------------------------------------------------
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com 
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: DynamoDbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: !GetAtt ViewStatsTable.Arn
  


  # ---------------------------------------------------------------------------
  # Resource: IAM Execution Role allowing API Gateway <-> Step Functions
  # ---------------------------------------------------------------------------
  ApiStepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsSyncExecuteAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartSyncExecution
                Resource: 
                  - !Ref GetItemStateMachine
                  - !Ref PutItemStateMachine

  # ---------------------------------------------------------------------------
  # Resource: DynamoDB Table for Product Details
  # ---------------------------------------------------------------------------
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH


  # ---------------------------------------------------------------------------
  # Resource: DynamoDB Table for Licences
  # ---------------------------------------------------------------------------
  LicencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: licences
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: productId
          KeyType: RANGE

  # ---------------------------------------------------------------------------
  # Resource: DynamoDB Table for Viewing Statistics
  # ---------------------------------------------------------------------------
  ViewStatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: view_stats
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: videoUrl
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: videoUrl
          KeyType: RANGE


  # ---------------------------------------------------------------------------
  # Resource: Lambda Function for Shopify App Backend
  # ---------------------------------------------------------------------------
  ShopifyAppLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'shopify-backend-handler'
      Runtime: nodejs24.x                    # Uses modern, LTS Node.js runtime
      Handler: 'index.handler'                 # Points to export named 'handler' in index.js file
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15                            # Maximum runtime execution limit (in seconds)
      MemorySize: 512                        # Allocated RAM size (in MB)
      Environment:
        Variables:
          # Pass database info directly; AWS SDK detects IAM credentials automatically
          SESSION_TABLE_NAME: 'shopify_sessions' 
          LOG_LEVEL: info
      Code: ./src
    Metadata: # Adds esbuild bundling support
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        EntryPoints: 
          - index.js  


  # =========================================================================
  # State Machine Step Function to read/write from/to DynamoDb.  This sits
  # in-between API HTTP Gateway and DynamoDb since HTTP Gateways can't natively
  # connect to DynamoDb 
  # =========================================================================
  GetItemStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: GetItemFromDynamoDB
      StateMachineType: EXPRESS
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Fetch an item from DynamoDB",
          "StartAt": "DynamoDBGetItem",
          "States": {
            "DynamoDBGetItem": {
              "Type": "Task",
              "Resource": "arn:aws:states:::aws-sdk:dynamodb:getItem",
              "Parameters": {
                "TableName": "${ViewStatsTable}",
                "Key": {
                  "customerId": { "S.$": "$.customerId" }
                }
              },
              "End": true
            }
          }
        }

  PutItemStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: PutItemToDynamoDB
      StateMachineType: EXPRESS
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Save a payload straight into DynamoDB",
          "StartAt": "DynamoDBPutItem",
          "States": {
            "DynamoDBPutItem": {
              "Type": "Task",
              "Resource": "arn:aws:states:::aws-sdk:dynamodb:putItem",
              "Parameters": {
                "TableName": "${ViewStatsTable}",
                "Item": {
                  "customerId": { "S.$": "$.customerId" },
                  "videoUrl": { "S.$": "$.videoUrl" },
                  "uniqueSeconds": { "N": "$.uniqueSeconds" },
                  "coveragePercent": { "N": "$.coveragePercent" },
                  "timestamp": { "N": "$.timestamp" }
                }
              },
              "End": true
            }
          }
        }


  # ---------------------------------------------------------------------------
  # Resource: HTTP API Gateway (API Gateway v2)
  # used for all requests that go to the Lambda (i.e. not viewing stats)
  # ---------------------------------------------------------------------------
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: 'shopify-backend-http-api'
      ProtocolType: HTTP
      Description: 'HTTP API Gateway routing traffic to the Shopify backend Lambda'
      CorsConfiguration:
        AllowOrigins:
          - "https://extensions.shopifycdn.com"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Shopify-Topic 
          - X-Shopify-Shop-Domain
          - X-Shopify-Hmac-Sha256
          - X-Shopify-Api-Client-Id
        MaxAge: 300

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  HttpApiLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ShopifyAppLambdaFunction.Arn
      PayloadFormatVersion: '2.0'
  
  # HTTP API does not have a direct service integration with DynamoDb (unlike REST API)
  # so go through a Step Function for GET/Get-Item
  HttpApiGetStepFunctionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0" # Must be 1.0 for AWS service integration subtypes
      CredentialsArn: !GetAtt ApiStepFunctionsExecutionRole.Arn
      RequestParameters:
        StateMachineArn: !Ref GetItemStateMachine
        # This extracts the 'id' variable out of your HTTP route path (e.g., /viewstats/{customerId})
        # and passes it as JSON input into the Step Function execution payload
        Input: "{\"customerId\": \"$request.path.customerId\"}"

  # ... and same for POST/Put-Item
  HttpApiPostStepFunctionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0"
      CredentialsArn: !GetAtt ApiStepFunctionsExecutionRole.Arn
      RequestParameters:
        StateMachineArn: !Ref PutItemStateMachine
        # Forwards the raw HTTP request body string directly as the input to Step Functions
        Input: "$request.body"

  # POST /products/{productId+}
  PostProductRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /products/{productId+}'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # GET /products/{productId+}
  GetProductRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /products/{productId+}'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # POST /webhooks/orders/paid
  WebhooksOrdersPaidRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /webhooks/orders/paid'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # GET /myvideos/{customerId}
  GetMyVideosRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /myvideos/{customerId}'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # GET /player-token
  PlayerTokenRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /player-token'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # GET /player/{customerId}
  PlayerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /player/{customerId}'
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref HttpApiLambdaIntegration

  # POST /viewstats -> step-function -> DynamoDb
  PostStatsRoute: 
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /viewstats'
      Target: !Sub 'integrations/${HttpApiPostStepFunctionIntegration}'
  # TODO: JWT authentication
  
  # GET /viewstats -> step-function -> DynamoDb
  GetStatsRoute: 
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /viewstats/{customerId}'
      Target: !Sub 'integrations/${HttpApiGetStepFunctionIntegration}'
  # TODO: JWT authentication

  LambdaPermissionForHttpApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ShopifyAppLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*'


  # ---------------------------------------------------------------------------
  # configure logging
  # ---------------------------------------------------------------------------
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # The LogGroupName must strictly follow this pattern to intercept Lambda logs
      LogGroupName: !Sub "/aws/lambda/shopify-backend-handler"
      RetentionInDays: 30



Outputs:
  
  HttpApiUrl:
    Description: 'The URL of the HTTP API endpoint. Vimeo Domain-Level security should use this domain'
    Value: !GetAtt HttpApi.ApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-HttpApiUrl'

  