# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89831ce5616715f0ecd725e5c3d8c597"
name = "viewpass"
application_url = "https://fhi0q3qzzl.execute-api.us-east-1.amazonaws.com/" # API Gateway URL
                # Can test sending a webhook while `shopify app dev` is running locally with
                # `shopify app webhook trigger --topic=orders/create --address=https://fhi0q3qzzl.execute-api.us-east-1.amazonaws.com/webhooks/orders/create --delivery-method=http --api-version=2026-01`
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]            # requires read_orders access scope
  uri = "/webhooks/orders/paid"       # NB: Bogus Payment Gateway in Dev Site won't trigger this
                                      # so for testing use Admin > Orders > Create Order > Mark as Paid
  


[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true   # do we need? (change to False?)

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

