name: Validate CloudFormation Template

on:
  push:
    paths:
      - 'aws-stack.yml'
  pull_request:
    paths:
      - 'aws-stack.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your target AWS region

      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body file://aws-stack.yml
